services:
  envoy:
    image: envoyproxy/envoy:v1.31-latest
    hostname: envoy
    ports:
      - "8080:8080"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
      - ./target/wasm32-wasip1/release:/etc/envoy/proxy-wasm-plugins
    networks:
      - envoymesh
  go-httpbin:
    image: mccutchen/go-httpbin
    hostname: go-httpbin
    ports:
      - "8081:8081"
    networks:
      - envoymesh
    environment:
      - PORT=8081
networks:
  envoymesh: {}